// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsTDNxX2lv6Ufmp26rnx8wsPLeDziZGuI',
    appId: '1:9024077500:web:72056c53dc10b7f80d5ab9',
    messagingSenderId: '9024077500',
    projectId: 'mychattapp-f7594',
    authDomain: 'mychattapp-f7594.firebaseapp.com',
    storageBucket: 'mychattapp-f7594.appspot.com',
    measurementId: 'G-ZWXQ2KTWP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVqU9KcN8r5hqnAFOcm6fvhkGEBIYVPw',
    appId: '1:9024077500:android:e3ac348c18d2560e0d5ab9',
    messagingSenderId: '9024077500',
    projectId: 'mychattapp-f7594',
    storageBucket: 'mychattapp-f7594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1HmspuQK0k6IfNCYhHx706PGTNIxyLY',
    appId: '1:9024077500:ios:c52dc9b2c5c0fd040d5ab9',
    messagingSenderId: '9024077500',
    projectId: 'mychattapp-f7594',
    storageBucket: 'mychattapp-f7594.appspot.com',
    iosClientId: '9024077500-nfj8uvgaq3bso8gd61uguqcm5en889k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chataplication',
  );
}
